[package]
name = "chess"
version = "1.0.0"
edition = "2021"

[dependencies]
yew = "0.19"
gloo = "0.6"

[dependencies.web-sys]
version = "0.3.56"
features = [
"DomRect",
"Element",
"HtmlElement",
"SvgElement",
]
